openapi: 3.1.0
info:
  title: Huebflix API
  description: Huebflix API
  version: 1.0.0
servers:
  - url: 'https://www.huebflix.de/api/v1'
    description: Huebflix production API
  - url: 'http://localhost:8080/api/v1'
    description: Huebflix local API
paths:
  /openapi:
    get:
      summary: Get OpenAPI specification
      responses:
        200:
          description: "OpenAPI specification"
components:
  schemas: {}
